### ISSUE TITLE
关于钱包的助记词建议

### ISSUE THREAD

**Issue by yxyhack** [vitelabs/vite-web-wallet#8]
![_20181128144716](https://user-images.githubusercontent.com/8045529/49134011-0ea38a00-f31d-11e8-9600-b1f8ed96fc24.png)
不建议将助记词存在本地，如果本地的服务器被黑客攻击，取得了权限，那么存在本地的助记词会被窃取。即便是使用了密码进行加密，通过逆向分析钱包的代码，还原助记词也只是时间问题。
建议的方式是在钱包初始化阶段，建议用户将助记词加密保存在本机以外的地方。然后本地将助记词和原始明文私钥销毁，在使用过程中，仅通过用户最近设置的密码来动态解密私钥在内存中（不要写文件）。PS:即便这样也并不是绝对安全的，但可以更好的保护原始私钥。

**Comment by lovelycs** [comment]
实在很抱歉没有及时回复。
暴力破解是一种手段，但花费的时间太久。
假设可能的组合为，2^127；计算机平均计算频率为  2^64.4753/s；那么大概需要 210,400,000,000 年；
但为了避免黑客攻击，确实应该给用户更多的自主权（比如增加清空加密信息功能，调节加密难度等等，形式上我们会认真讨论一下），十分感谢您的建议！！！
